name = "nirbenu-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "nirbenu-db"
database_name = "nirbenu-db"
database_id = "937b4d3c-b1ae-4f14-a075-8ca06841b850"

[[r2_buckets]]
binding = "nirbenu-storage"
bucket_name = "nirbenu-storage"

[vars]
BASE_URL = "https://nirbenu-api.alfredhafizmc.workers.dev/"
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
PUSHER_APP_ID = ""
PUSHER_KEY = ""
PUSHER_SECRET = ""
PUSHER_CLUSTER = "ap2"
RESEND_API_KEY = ""

[env.production]
BASE_URL = "https://nirbenu.pages.dev"
